return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      clangd = {},
      clang_format = {},
      astro_language_server = {},
      bash_language_server = {},
      css_lsp = {},
      emmet_ls = {},
      eslint = {},
      fixjson = {},
      html = {},
      htmlbeautifier = {},
      intelephense = {},
      java_language_server = {},
      jsonls = {},
      marksman = {},
      php_cs_fixer = {},
      prettierd = {},
      sqlfmt = {},
      stylua = {},
      svelte = {},
      tailwindcss = {},
      tsserver = {},
      volar = {},
      xmlformatter = {},
    },
  },
}
